Input parsing
Jpinyot/42_n-puzzle pull request #4
Opened 2020-10-02 10:24 UTC by Jpinyot

Create new Class InputParse:
- Get puzzle from FD.
- Check if errors.
- Translate puzzle.
- Translate puzzle back.

2020-10-02 10:28 UTC, Jpinyot reviewed
Thing of better name for some methods?!.

2020-10-02 13:18 UTC, mfigueras11 commented on includes/inputParser.h
> +		void		setTileAsChecket(const unsigned char& pos) {tileChecker_.at(pos) = true;}
Rename -> fix typo setTileAsChecked

2020-10-02 13:30 UTC, mfigueras11 requested changes
Fix typo, everything else seems good

2020-10-05 07:26 UTC, Jpinyot commented on includes/inputParser.h
> +		void		setTileAsChecket(const unsigned char& pos) {tileChecker_.at(pos) = true;}
commit 1570316

2020-10-05 07:59 UTC, merged